# Generated by Django 4.2 on 2024-05-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_max_establishments"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
