# Generated by Django 4.2 on 2024-05-05 14:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0006_establishment_happyhours_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="establishment",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.DeleteModel(
            name="QRCode",
        ),
    ]
