# Generated by Django 4.2 on 2024-05-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0007_alter_establishment_location_delete_qrcode"),
        ("partner", "0007_feedback_feedbackanswer"),
    ]

    operations = []
