# Generated by Django 4.2 on 2024-05-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0008_merge_20240506_1550"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbackanswer",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="feedbackanswer",
            name="user",
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
        migrations.DeleteModel(
            name="FeedbackAnswer",
        ),
    ]
