# Generated by Django 4.2 on 2024-05-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0009_remove_feedbackanswer_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishment",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
